export interface User {
    displayName?: string,
    modifiedAt?: Date,
    uid?: string,
    email: string,
    acceptedConditions: boolean,
    profilePictureURL: string,
    followersAmount: number,
    followers: string[],
    followingAmount: number,
    following: string[]
    headerName: string | null,
    bio: string | null,
    age: number | null,
    gender: string | null,
    country: string | null,
    height: number | null,
    weight: number | null,
    sports: string[] | null,
}