export interface User {
    posts?: string[],
    comments?: string[],
    followersAmount: number,
    followers: string[],
    followingAmount: number,
    following: string[]    
    acceptedConditions: boolean,
    displayName?: string,
    modifiedAt?: Date,
    uid: string,
    email: string,
    profilePic: string,
    headerName: string | null,
    bio: string | null,
    age: number | null,
    gender: string | null,
    country: string | null,
    height: number | null,
    weight: number | null,
    sports: string[] | null,
}